name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest
    env:
      BCRYPT_SALTS: ${{ secrets.BCRYPT_SALTS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm run test-ci
